apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake-atlan
spec:
  provider:
    fake:
      data:
        - key: "atlan-data-catalog-plugin"
          valueMap:
            ATLAN_OAUTH_CLIENT_ID: id
            ATLAN_OAUTH_CLIENT_SECRET: secret
